# Generated by Django 4.2.1 on 2023-05-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'db_table_comment': 'Таблица с классами',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Предмет')),
                ('groups', models.ManyToManyField(to='API_LearnFS.group')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table_comment': 'Таблица с предметами',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Загаловок/название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('subs_clases', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_LearnFS.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table_comment': 'Таблица с темами',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_LearnFS.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table_comment': 'Таблица с тестами по какой-либо теме',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Конспект')),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_LearnFS.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Конспект',
                'verbose_name_plural': 'Конспекты',
                'db_table_comment': 'Таблица с ответами конспектами по какой-либо теме',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_LearnFS.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table_comment': 'Таблица с вопросами',
            },
        ),
        migrations.CreateModel(
            name='Ans_Que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('isRight', models.BooleanField(default=False, verbose_name='Правильность')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_LearnFS.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'db_table_comment': 'Таблица с ответами на вопросы',
            },
        ),
    ]
