# Generated by Django 4.2.1 on 2023-05-27 20:48

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API_LearnFS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='HTML'),
        ),
    ]
