# Generated by Django 4.2.1 on 2023-05-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_LearnFS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(to='API_LearnFS.group', verbose_name='Класс'),
        ),
    ]
