# Generated by Django 4.2.1 on 2023-05-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_LearnFS', '0002_alter_subject_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ans_que',
            old_name='questions',
            new_name='questions_id',
        ),
    ]
